server:
  port: 9411
spring:
  application:
    name: zipkin-server-elk
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: 127.0.0.1:5608

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
