server:
  port: 8762
spring:
  application:
    name: service-provider
eureka:
  client:
    serviceUrl:
    #高可用配置
#      defaultZone: http://peer1:8751/eureka/
      defaultZone: http://localhost:8761/eureka/