server:
  port: 8883

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      fail-fast: true
      discovery:
#      从配置中心读取文件。高可用配置discovery
        enabled: true
#        配置中心的servieId，即服务名。高可用配置discovery
#        读取配置文件不再写ip地址，而是服务名，这时如果配置服务部署多份，通过负载均衡，从而高可用。
        service-id: config-server
## 开启消息跟踪
#      bus:
#         trace:
#             enabled: true

  rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: fnuser
        password: fnuser
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      刷新时，关闭安全验证
management:
  security:
     enabled: false