server:
  port: 8752
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8751/eureka/
    register-with-eureka: false
    fetch-registry: false
  #关闭保护模式
  server:
    enable-self-preservation: false
